name: bhatti_pos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  get: ^4.6.5
  http: ^0.13.5
  flutter_slidable: ^2.0.0
  url_launcher: ^6.1.6
  fluttertoast: ^8.1.1
  # animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/background/
    - assets/logo/
    - assets/icons/
  